title: Tibor Krleža # your name (or website title) here
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Startup indie game developer.
  <br><br>
  You can contact me at any time at <a href="tiborkrleza@gmail.com">tiborkrleza@gmail.com</a>.
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
